### ISSUE TITLE
Auth 2.0 Part II: Revenge of AuthZ

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#1190]
Sequel to: https://github.com/aspnet/Security/issues/1179

### Host Wave PRs:
- [x] HttpSys: https://github.com/aspnet/HttpSysServer/pull/325
- [x] IISIntegration: https://github.com/aspnet/IISIntegration/pull/338
- [ ] AspNetCoreModule: https://github.com/aspnet/IISIntegration/issues/371
- [x] ServerTests

### Cleanup PRs/Issues:
- [x] Options Initializer support: https://github.com/aspnet/Options/pull/187
- [x] Replace Auth double locking with Initialize for fixup https://github.com/aspnet/Security/pull/1206
- [ ] Rationalize AddXyz() behavior: https://github.com/aspnet/Security/issues/1191 PR: https://github.com/aspnet/MetaPackages/pull/118
- [ ] Obsolete HttpAbstractions: https://github.com/aspnet/HttpAbstractions/pull/806
- [ ] Revisit Events/Context https://github.com/aspnet/Security/issues/1181
- [ ] Reenable ApiCheck
- [ ] Fixup all the samples to use new Identity API again

### Issues:
- [ ] Need docs/Migration: https://github.com/aspnet/Docs/issues/3054

### Authorization: https://github.com/aspnet/Security/pull/1193
- [x] 401 vs 403, error/diagonstics: https://github.com/aspnet/Security/issues/901
- [x] Shared AuthZPolicyEvaluator: https://github.com/aspnet/Security/pull/1148
- [x] Add IAuthorizationHandlerProvider: https://github.com/aspnet/Security/issues/1176
#

**Comment by ryanelian** [comment]
Hello, I've been reading the threads from https://github.com/aspnet/Announcements/issues/232

I have a question, let's say I have an authentication setup like below:

```cs
app.UseWhen(context => context.Request.Path.Value.StartsWith("/api", StringComparison.OrdinalIgnoreCase), builder =>
{
    builder.UseCookieAuthentication(new CookieAuthenticationOptions
    {
        AuthenticationScheme = AuthService.CookieAuthenticationScheme,
        AutomaticAuthenticate = true,

        AutomaticChallenge = false,
        LoginPath = null,
        LogoutPath = null,
        AccessDeniedPath = null
    });
});

app.UseWhen(context => context.Request.Path.Value.StartsWith("/api", StringComparison.OrdinalIgnoreCase) == false, builder =>
{
    builder.UseCookieAuthentication(new CookieAuthenticationOptions
    {
        AuthenticationScheme = AuthService.CookieAuthenticationScheme,
        AutomaticAuthenticate = true,

        AutomaticChallenge = true,
        LoginPath = "/auth/login",
        LogoutPath = "/auth/logout",
        AccessDeniedPath = "/home/denied",
    });
});
```

The goal of above code is to prevent API-type endpoints (that returns JSON) to redirect user to login page when authentication fails. (Instead just return 401 Unauthorized or 403 Forbidden)

How can I do this using the new authentication middleware?

Thank you for advice, in advance.

**Comment by Tratcher** [comment]
@ryanelian The Policy recommendations in https://github.com/aspnet/Security/issues/1062 still work for your scenario.

**Comment by ryanelian** [comment]
I just read that link. I don't understand.

If I'm not mistaken, I'm supposed to put a policy in my Authorize attributes so it take effect, like: `[Authorize("ApiPolicy")]`. But I don't see how **that** is relevant for branching my authentication middleware. Besides,

- I do not wish to pollute my Authorize attributes with policy just for doing this...

- If you have seen my above example, both middleware uses the **same** scheme. How am I supposed to do that?

Can you please provide code sample specifically for the above case, please?

**Comment by HaoK** [comment]
You can't do that anymore, each scheme is now unique, and since they are no longer middleware you can't branch your app to use the same logical scheme for different middleware.  You will need to setup two schemes, "Api", "Cookies"

**Comment by ryanelian** [comment]
I have a mixed feeling about this. I feel that the change unnecessarily complicates the development. The service-based authentication feels like 10 steps backward to me, idk.

There should be a simple way to define schemes used for routes condition...

But okay, let's say I can just explicitly tell the API Controller to use `Api` scheme, I'll just need to set the `CookieName` to the same name as the `Cookie` scheme, is that correct?

**Comment by HaoK** [comment]
If there was a way to specify services per route/request/context that would just work, but there isn't today...

I'm not sure what you are asking about with the cookie name, but you can keep using the cookies as the DefaultAuthenticateScheme for your non API requests, if your API controller is going to explicitly ask for the API.

**Comment by ryanelian** [comment]
> I'm not sure what you are asking about with the cookie name

Let's say in 1.1, I make a cookie authentication scheme called `MyAppIdentity`.

Apparently ASP.NET will make a cookie for that scheme named `.AspNetCore.MyAppIdentity`.

Now you're advising me to make 2 separate authentication schemes, 1 = cookie for UI, 1 = cookie for API. Let's say I do that, 
- Authentication scheme for UI-type Controller = `Cookie`
- Authentication scheme for API-type Controllers = `Api`.

However, the cookie for the schemes will be different, no?
- Cookie name for `Cookie` scheme = `.AspNetCore.Cookie`
- Cookie name for `Api` scheme = `.AspNetCore.Api`

Thus the question, **can I use two different cookie authentication schemes, but targets the same cookie key / store / name?**

**Comment by HaoK** [comment]
I don't think there should be any issues targeting the same cookie name with different schemes, you might have to make sure to configure the TicketFormat for both schemes to be the same if you are going to read the same cookie in either scheme.

**Comment by ryanelian** [comment]
Awesome.

So setting the same `CookieName` is not enough?

Sorry, I haven't heard about TicketFormat before. I saw https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/compatibility/cookie-sharing but I don't really get what I am supposed to configure.

Mind providing code sample for this? Thanks again.

**Comment by Tratcher** [comment]
Just CookieName should be enough.

That said, with AutomaticAuthenticate and AutomaticChallenge removed from CookieAuthOptions, why do you still need two auth middleware? Nulling out the paths has never had any effect.

**Comment by ryanelian** [comment]
> That said, with AutomaticAuthenticate and AutomaticChallenge removed from CookieAuthOptions, why do you still need two auth middleware? Nulling out the paths has never had any effect.

Oh did they in 1.1? TIL.

I thought if you don't set them as false / nulled out , they'll kick you to login / access denied path, which is not preferable for API-type Controllers. (You'd want instead just a status code response indicating that the request is unauthorized / forbidden)

I don't know, I've been using that technique since forever, never noticed if they don't have any effects anymore or something.

**Comment by Tratcher** [comment]
No, that behavior was caused by AutomaticChallenge = false, the middleware was being bypassed for challenges. Null paths were always set to defaults by the middleware.

I suspect that 401 status code was being set by the IISIntegration middleware, which always assumed windows auth was enabled (AutomaticChallenge = true). This is going away soon: https://github.com/aspnet/IISIntegration/issues/371.

A different approach that would still work (without two middleware) is to use the events to control the behavior: https://github.com/aspnet/Security/blob/1f5a27e20adf5438adcd9caf8587230307b685ce/src/Microsoft.AspNetCore.Authentication.Cookies/Events/CookieAuthenticationEvents.cs#L43

**Comment by ryanelian** [comment]
> A different approach that would still work (without two middleware) is to use the events to control the behavior:

```cs
public Func<CookieRedirectContext, Task> OnRedirectToLogin { get; set; } = context =>
{
    if (IsAjaxRequest(context.Request))
    {
        context.Response.Headers["Location"] = context.RedirectUri;
        context.Response.StatusCode = 401;
    }
    else
    {
        context.Response.Redirect(context.RedirectUri);
    }
    return TaskCache.CompletedTask;
};
```

Ohhh yesss, that's what I'm talking about. 👍 🌶 🔥 

Will that behavior be enabled by default on the 2.0.0 Authentication Cookie? 
So I don't need 2 authentication schemes after all?

**Comment by Tratcher** [comment]
The Location header does not trigger redirects, the status code does.

**Comment by ryanelian** [comment]
Oh okay.

So to recap, the new cookie authentication scheme will not redirect when it's AJAX request, by default, but instead returns 401 when not authenticated, or 403 when access denied.
Therefore I don't need 2 different authentication schemes just to handle that behavior in 2.0.0.

Am I understanding that correctly?

Alrighty then, thank you guys. Great job over there, keep it up. 👍

**Comment by Tratcher** [comment]
Note 1.0 behaved the same way.

**Comment by ryanelian** [comment]
Huh... Now that's curious. I wonder why I did that in the first place then.

I vaguely remembered long ago that it bounced me to other page when my Angular service hits an unauthorized / access denied controller.

Oh well. Thanks for info.

**Comment by HaoK** [comment]
e940cdb36bc7617af3d762ff9cc853a8fef55b0a
